image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Environment
    init: |
      sudo apt-get update
      sudo apt-get install -y vagrant
      vagrant plugin install vagrant-libvirt

ports:
  - port: 162
    protocol: "UDP"
    onOpen: ignore
  - port: 22
    onOpen: ignore

vscode:
  extensions:
    - hashicorp.terraform
