image:
  file: .gitpod.Dockerfile

ports:
  - port: 162
    protocol: udp
  - port: 22
    onOpen: ignore

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y vagrant virtualbox
      vagrant plugin install vagrant-libvirt
      vagrant up
